### ISSUE TITLE
v1.4.1-01  widescreen patch not working

### ISSUE THREAD

**Issue by nr1995** [spitfirex86/Ray2Fix#19]
Hi,
I'm using the latest version of Ray2Fix,
and I've selected 2560x1440 with widescreen patch checked (and without).
Either way it's 4:3.
N

**Comment by spitfirex86** [comment]
You'll have to be a little patient. GOG completely broke ray2fix with their out-of-nowhere "patch" and I did not have time to fix it yet. In the meantime, I'd recommend using the old version from before GOG broke it.

**Comment by spitfirex86** [comment]
Can you try again with a fresh copy of the game and the latest version of Ray2Fix?

Apparently the new GOG release works just fine, the issues were caused by the fact that updating overwrites the game files and so requires reinstalling Ray2Fix afterwards once more.

**Comment by Jawzper** [comment]
Hi, I have just today tried the latest patch with a fresh installation of Rayman 2. It looks like I'm still stuck in the default resolution at this time. I'm using Wine/Proton via Heroic so I found some info relating to resolution in my logs, maybe you will find the information useful:

```
(20:43:43) [INFO]:    Launching "Rayman 2: The Great Escape" (gog)

(20:43:44) [INFO]:    Native? false

(20:43:44) [INFO]:    Installed in: /home/user/Games/Heroic/Rayman 2 

(20:43:44) [INFO]:    System Info: 

CPU: 16x AMD Ryzen 7 9800X3D 8-Core Processor

Memory: 66.98 GB (used: 11.99 GB)

GPUs:

  GPU 0:

    Name: Advanced Micro Devices, Inc. [AMD/ATI] NITRO+ RX 7900 XTX Vapor-X

    IDs: D=744c V=1002 SD=e471 SV=1da2

    Driver: amdgpu

OS: EndeavourOS 6.18.2-arch2-1 (linux)

The current system is not a Steam Deck

We are not running inside a Flatpak container

Software Versions:

  Heroic: 2.18.1 "Waterfall Beard" Jorul

  Legendary: 0.20.37 Exit 17 (Heroic)

  gogdl: 1.1.2

  comet: comet 0.2.0

  Nile: 1.1.2 Will A. Zeppeli

(20:43:44) [INFO]:    Game Settings: {

  "autoInstallDxvkNvapi": false,

  "preferSystemLibs": false,

  "enableEsync": true,

  "enableFsync": true,

  "enableWineWayland": false,

  "enableHDR": false,

  "enableWoW64": false,

  "nvidiaPrime": false,

  "enviromentOptions": [],

  "wrapperOptions": [],

  "showFps": false,

  "showMangohud": false,

  "useGameMode": true,

  "useSteamRuntime": false,

  "battlEyeRuntime": true,

  "eacRuntime": true,

  "language": "",

  "beforeLaunchScriptPath": "",

  "afterLaunchScriptPath": "",

  "verboseLogs": true,

  "wineVersion": {

    "bin": "/home/user/.config/heroic/tools/proton/GE-Proton-latest/proton",

    "name": "Proton - GE-Proton-latest",

    "type": "proton"

  },

  "winePrefix": "/home/user/Games/Heroic/Prefixes/default/Rayman 2 The Great Escape"

} 

(20:43:44) [INFO]:    Winetricks packages: 

(20:43:49) [INFO]:    Launching Rayman 2: The Great Escape: HEROIC_APP_NAME=1207658940 HEROIC_APP_RUNNER=gog GAMEID=umu-0 HEROIC_APP_SOURCE=gog STORE=gog STEAM_COMPAT_INSTALL_PATH="/home/user/Games/Heroic/Rayman 2" LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/user/.steam/steam WINEPREFIX="/home/user/Games/Heroic/Prefixes/default/Rayman 2 The Great Escape" STEAM_COMPAT_DATA_PATH="/home/user/Games/Heroic/Prefixes/default/Rayman 2 The Great Escape" PROTONPATH=/home/user/.config/heroic/tools/proton/GE-Proton-latest WINE_FULLSCREEN_FSR=0 PROTON_DISABLE_NVAPI=1 PROTON_EAC_RUNTIME=/home/user/.config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/user/.config/heroic/tools/runtimes/battleye_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-Rayman 2" PROTON_LOG_DIR=/home/user WINEDEBUG=+fixme DXVK_LOG_LEVEL=info VKD3D_DEBUG=fixme GOGDL_CONFIG_PATH=/home/user/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.config/heroic/gog_store/auth.json launch "/home/user/Games/Heroic/Rayman 2" 1207658940 --no-wine --wrapper "/usr/bin/gamemoderun "/home/user/.config/heroic/tools/runtimes/umu/umu_run.py"" --platform windows 

(20:43:49) [INFO]:    Game Output:

gamemodeauto: 

gamemodeauto: 

INFO: umu-launcher version 1.3.0 (3.13.11 (main, Dec  7 2025, 13:01:45) [GCC 15.2.1 20251112])

INFO: steamrt3 is up to date

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

ProtonFixes[742716] INFO: Running protonfixes on "GE-Proton10-26", build at 2025-12-07 22:33:15+00:00.

ProtonFixes[742716] INFO: Running checks

ProtonFixes[742716] INFO: All checks successful

ProtonFixes[742716] WARN: Game title not found in CSV

ProtonFixes[742716] INFO: Non-steam game UNKNOWN (umu-0)

ProtonFixes[742716] INFO: GOG store specified, using GOG database

ProtonFixes[742716] INFO: No global defaults found for UNKNOWN (umu-0)

ProtonFixes[742716] INFO: Non-steam game UNKNOWN (umu-0)

ProtonFixes[742716] INFO: GOG store specified, using GOG database

ProtonFixes[742716] INFO: No global protonfix found for UNKNOWN (umu-0)

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

Proton: /home/user/Games/Heroic/Rayman 2/Rayman2.exe

Proton: Executable a unix path, launching with /unix option.

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

wineserver: NTSync up and running!

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

002c:fixme:winediag:loader_init wine-staging 10.0 is a testing version containing experimental patches.

002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

0040:fixme:ntoskrnl:driver_stub 0000000000249D30 L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\pci" stub!

0040:fixme:ntoskrnl:driver_stub 0000000000249F80 L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\hidusb" stub!

0040:fixme:ntoskrnl:driver_stub 000000000024AD50 L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\Disk" stub!

0050:fixme:ntoskrnl:kernel_object_from_handle No constructor for type L"Token"

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

0094:fixme:ntoskrnl:driver_stub 0000000000249D30 L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\pci" stub!

0094:fixme:ntoskrnl:driver_stub 0000000000249F80 L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\hidusb" stub!

0094:fixme:ntoskrnl:driver_stub 000000000024AD50 L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\Disk" stub!

00a0:fixme:ntoskrnl:kernel_object_from_handle No constructor for type L"Token"

00b4:err:hid:get_container_id_for_usb_udev_device Failed to get parent device.

00b4:err:hid:get_container_id_for_usb_udev_device Failed to get parent device.

00b4:err:hid:get_container_id_for_usb_udev_device Failed to get parent device.

009c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\winebth": c0000142

0034:fixme:service:scmdatabase_autostart_services Auto-start service L"winebth" failed to start: 1114

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

00d4:fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\X:\\.config\\heroic\\tools\\proton\\GE-Proton-latest\\files\\share\\wine/../xalia/xalia.exe"

00d4:fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\X:\\.config\\heroic\\tools\\proton\\GE-Proton-latest\\files\\share\\wine/../xalia/xalia.exe"

00d4:fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\X:\\.config\\heroic\\tools\\proton\\GE-Proton-latest\\files\\share\\wine/../xalia/xalia.exe"

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

0114:fixme:oleacc:find_class_data unhandled window class: L"#32769"

0114:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.

0114:fixme:uiautomation:default_uia_provider_callback Default ProviderType_NonClientArea provider unimplemented.

0114:fixme:oleacc:find_class_data unhandled window class: L"#32769"

0114:fixme:uiautomation:base_hwnd_fragment_get_FragmentRoot 000000000081C288, 000000000021F9A0: stub!

0114:fixme:uiautomation:base_hwnd_fragment_GetEmbeddedFragmentRoots 000000000081C288, 000000000021F9B0: stub!

info:  Game: Rayman2.exe

info:  DXVK: v2.7.1-310-g0118eaff27d0d96

info:  Build: x86 gcc 14.2.0

info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x799435f0

info:  Extension providers:

info:    Platform WSI

info:    OpenVR

info:  OpenVR: could not open registry key, status 2

warn:  OpenVR: Failed to initialize OpenVR

info:    OpenXR

info:  Enabled instance extensions:

info:    VK_EXT_surface_maintenance1

info:    VK_KHR_get_surface_capabilities2

info:    VK_KHR_surface

info:    VK_KHR_win32_surface

info:  Found device: AMD Radeon RX 7900 XTX (RADV NAVI31) (radv 25.3.2)

info:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT

info:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT

info:  Process set as DPI aware

info:  Creating device:

info:  AMD Radeon RX 7900 XTX (RADV NAVI31):

info:    Driver   : radv 25.3.2

info:  Queues:

info:    Graphics : (0, 0)

info:    Transfer : (1, 0)

info:    Sparse   : (0, 0)

info:  Memory:

info:    Heap 0: 31.18 GiB

info:    Budget: 30.84 GiB

info:      Type  2: HOST_VISIBLE | HOST_COHERENT

info:      Type  5: HOST_VISIBLE | HOST_COHERENT | HOST_CACHED

info:      Type  6: HOST_VISIBLE | HOST_COHERENT | HOST_CACHED

info:      Type  8: HOST_VISIBLE | HOST_COHERENT | DEVICE_COHERENT | DEVICE_UNCACHED

info:      Type 10: HOST_VISIBLE | HOST_COHERENT | HOST_CACHED | DEVICE_COHERENT | DEVICE_UNCACHED

info:    Heap 1: 23.98 GiB (DEVICE_LOCAL)

info:    Budget: 19.8 GiB

info:      Type  0: DEVICE_LOCAL

info:      Type  1: DEVICE_LOCAL

info:      Type  3: DEVICE_LOCAL | HOST_VISIBLE | HOST_COHERENT

info:      Type  4: DEVICE_LOCAL | HOST_VISIBLE | HOST_COHERENT

info:      Type  7: DEVICE_LOCAL | DEVICE_COHERENT | DEVICE_UNCACHED

info:      Type  9: DEVICE_LOCAL | HOST_VISIBLE | HOST_COHERENT | DEVICE_COHERENT | DEVICE_UNCACHED

info:  Enabled extensions:

info:    VK_EXT_attachment_feedback_loop_layout

info:    VK_EXT_conservative_rasterization

info:    VK_EXT_custom_border_color

info:    VK_EXT_depth_clip_enable

info:    VK_EXT_depth_bias_control

info:    VK_EXT_descriptor_buffer

info:    VK_EXT_extended_dynamic_state3

info:    VK_EXT_fragment_shader_interlock

info:    VK_EXT_graphics_pipeline_library

info:    VK_EXT_hdr_metadata

info:    VK_EXT_line_rasterization

info:    VK_EXT_memory_priority

info:    VK_EXT_multi_draw

info:    VK_EXT_non_seamless_cube_map

info:    VK_EXT_robustness2

info:    VK_EXT_sample_locations

info:    VK_EXT_shader_module_identifier

info:    VK_EXT_shader_stencil_export

info:    VK_EXT_swapchain_maintenance1

info:    VK_EXT_transform_feedback

info:    VK_EXT_vertex_attribute_divisor

info:    VK_KHR_external_memory_win32

info:    VK_KHR_external_semaphore_win32

info:    VK_KHR_load_store_op_none

info:    VK_KHR_maintenance5

info:    VK_KHR_maintenance6

info:    VK_KHR_pipeline_library

info:    VK_KHR_present_id2

info:    VK_KHR_present_wait2

info:    VK_KHR_shader_float_controls2

info:    VK_KHR_swapchain

info:    VK_KHR_swapchain_mutable_format

info:    VK_KHR_win32_keyed_mutex

info:  Enabled features:

info:    depthBiasClamp                 : 1

info:    depthBounds                    : 1

info:    depthClamp                     : 1

info:    drawIndirectFirstInstance      : 1

info:    dualSrcBlend                   : 1

info:    fillModeNonSolid               : 1

info:    fragmentStoresAndAtomics       : 1

info:    fullDrawIndexUint32            : 1

info:    geometryShader                 : 1

info:    imageCubeArray                 : 1

info:    independentBlend               : 1

info:    logicOp                        : 1

info:    multiDrawIndirect              : 1

info:    multiViewport                  : 1

info:    occlusionQueryPrecise          : 1

info:    pipelineStatisticsQuery        : 1

info:    robustBufferAccess             : 1

info:    sampleRateShading              : 1

info:    samplerAnisotropy              : 1

info:    shaderClipDistance             : 1

info:    shaderCullDistance             : 1

info:    shaderFloat64                  : 1

info:    shaderImageGatherExtended      : 1

info:    shaderInt16                    : 1

info:    shaderInt64                    : 1

info:    shaderUniformBufferArrayDynamicIndexing : 1

info:    shaderSampledImageArrayDynamicIndexing : 1

info:    shaderStorageBufferArrayDynamicIndexing : 1

info:    shaderStorageImageArrayDynamicIndexing : 1

info:    sparseBinding                  : 1

info:    sparseResidencyBuffer          : 1

info:    sparseResidencyImage2D         : 1

info:    sparseResidencyImage3D         : 1

info:    sparseResidency2Samples        : 0

info:    sparseResidency4Samples        : 0

info:    sparseResidency8Samples        : 0

info:    sparseResidency16Samples       : 0

info:    sparseResidencyAliased         : 1

info:    shaderResourceResidency        : 1

info:    shaderResourceMinLod           : 1

info:    tessellationShader             : 1

info:    textureCompressionBC           : 1

info:    variableMultisampleRate        : 1

info:    vertexPipelineStoresAndAtomics : 1

info:    wideLines                      : 1

info:    shaderDrawParameters           : 1

info:    storagePushConstant16          : 1

info:    bufferDeviceAddress            : 1

info:    descriptorIndexing             : 1

info:    shaderUniformTexelBufferArrayDynamicIndexing : 1

info:    shaderStorageTexelBufferArrayDynamicIndexing : 1

info:    shaderUniformBufferArrayNonUniformIndexing : 1

info:    shaderSampledImageArrayNonUniformIndexing : 1

info:    shaderStorageBufferArrayNonUniformIndexing : 1

info:    shaderStorageImageArrayNonUniformIndexing : 1

info:    shaderUniformTexelBufferArrayNonUniformIndexing : 1

info:    shaderStorageTexelBufferArrayNonUniformIndexing : 1

info:    descriptorBindingSampledImageUpdateAfterBind : 1

info:    descriptorBindingUpdateUnusedWhilePending : 1

info:    descriptorBindingPartiallyBound : 1

info:    drawIndirectCount              : 1

info:    hostQueryReset                 : 1

info:    runtimeDescriptorArray         : 1

info:    samplerFilterMinmax            : 1

info:    samplerMirrorClampToEdge       : 1

info:    scalarBlockLayout              : 1

info:    shaderFloat16                  : 1

info:    shaderInt8                     : 1

info:    shaderOutputViewportIndex      : 1

info:    shaderOutputLayer              : 1

info:    timelineSemaphore              : 1

info:    uniformBufferStandardLayout    : 1

info:    vulkanMemoryModel              : 1

info:    dynamicRendering               : 1

info:    maintenance4                   : 1

info:    robustImageAccess              : 0

info:    pipelineCreationCacheControl   : 1

info:    shaderDemoteToHelperInvocation : 1

info:    shaderZeroInitializeWorkgroupMemory : 1

info:    synchronization2               : 1

info:  VK_EXT_attachment_feedback_loop_layout:

info:    attachmentFeedbackLoopLayout   : 1

info:  VK_EXT_conservative_rasterization:

info:    extConservativeRasterization   : 1

info:  VK_EXT_custom_border_color:

info:    customBorderColors             : 1

info:    customBorderColorWithoutFormat : 1

info:  VK_EXT_depth_clip_enable:

info:    depthClipEnable                : 1

info:  VK_EXT_depth_bias_control:

info:    depthBiasControl               : 1

info:    leastRepresentableValueForceUnormRepresentation : 1

info:    floatRepresentation            : 1

info:    depthBiasExact                 : 1

info:  VK_EXT_descriptor_buffer:

info:    descriptorBuffer               : 1

info:  VK_EXT_extended_dynamic_state3:

info:    extendedDynamicState3AlphaToCoverageEnable : 1

info:    extendedDynamicState3DepthClipEnable : 1

info:    extendedDynamicState3RasterizationSamples : 1

info:    extendedDynamicState3SampleMask : 1

info:    extendedDynamicState3LineRasterizationMode : 1

info:    extendedDynamicState3SampleLocationsEnable : 1

info:  VK_EXT_fragment_shader_interlock:

info:    fragmentShaderSampleInterlock  : 1

info:    fragmentShaderPixelInterlock   : 1

info:  VK_EXT_full_screen_exclusive:

info:    extFullScreenExclusive         : 0

info:  VK_EXT_graphics_pipeline_library:

info:    graphicsPipelineLibrary        : 1

info:  VK_EXT_hdr_metadata:

info:    extHdrMetadata                 : 1

info:  VK_EXT_line_rasterization:

info:    rectangularLines               : 1

info:    smoothLines                    : 1

info:  VK_EXT_memory_budget:

info:    extMemoryBudget                : 1

info:  VK_EXT_memory_priority:

info:    memoryPriority                 : 1

info:  VK_EXT_multi_draw:

info:    multiDraw                      : 1

info:  VK_EXT_non_seamless_cube_map:

info:    nonSeamlessCubeMap             : 1

info:  VK_EXT_pageable_device_local_memory:

info:    pageableDeviceLocalMemory      : 0

info:  VK_EXT_robustness2:

info:    robustBufferAccess2            : 1

info:    robustImageAccess2             : 1

info:    nullDescriptor                 : 1

info:  VK_EXT_sample_locations:

info:    extSampleLocations             : 1

info:  VK_EXT_shader_module_identifier:

info:    shaderModuleIdentifier         : 1

info:  VK_EXT_shader_stencil_export:

info:    extShaderStencilExport         : 1

info:  VK_EXT_swapchain_colorspace:

info:    extSwapchainColorSpace         : 0

info:  VK_EXT_swapchain_maintenance1:

info:    swapchainMaintenance1          : 1

info:  VK_EXT_transform_feedback:

info:    transformFeedback              : 1

info:    geometryStreams                : 1

info:  VK_EXT_vertex_attribute_divisor:

info:    vertexAttributeInstanceRateDivisor : 1

info:    vertexAttributeInstanceRateZeroDivisor : 1

info:  VK_KHR_external_memory_win32:

info:    khrExternalMemoryWin32         : 1

info:  VK_KHR_external_semaphore_win32:

info:    khrExternalSemaphoreWin32      : 1

info:  VK_KHR_load_store_op_none:

info:    khrLoadStoreOpNone             : 1

info:  VK_KHR_maintenance5:

info:    maintenance5                   : 1

info:  VK_KHR_maintenance6:

info:    maintenance6                   : 1

info:  VK_KHR_maintenance7:

info:    maintenance7                   : 0

info:  VK_KHR_pipeline_library:

info:    khrPipelineLibrary             : 1

info:  VK_KHR_present_id:

info:    presentId                      : 0

info:  VK_KHR_present_id2:

info:    presentId2                     : 1

info:  VK_KHR_present_wait:

info:    presentWait                    : 0

info:  VK_KHR_present_wait2:

info:    presentWait2                   : 1

info:  VK_KHR_shader_float_controls2:

info:    shaderFloatControls2           : 1

info:  VK_KHR_swapchain:

info:    khrSwapchain                   : 1

info:  VK_KHR_swapchain_maintenance1:

info:    swapchainMaintenance1          : 0

info:  VK_KHR_swapchain_mutable_format:

info:    khrSwapchainMutableFormat      : 1

info:  VK_KHR_win32_keyed_mutex:

info:    khrWin32KeyedMutex             : 1

info:  VK_NV_low_latency2:

info:    nvLowLatency2                  : 0

info:  VK_NV_raw_access_chains:

info:    shaderRawAccessChains          : 0

info:  VK_NVX_binary_import:

info:    nvxBinaryImport                : 0

info:  VK_NVX_image_view_handle:

info:    nvxImageViewHandle             : 0

info:  Descriptor sizes (set alignment: 64)

info:    Sampler              : 16

info:    Uniform buffer       : 16

info:    Storage buffer       : 16

info:    Uniform texel buffer : 16

info:    Storage texel buffer : 16

info:    Sampled image        : 32

info:    Storage image        : 32

info:  Memory type mask for sparse resources: 0x7ad

info:  Memory type mask for buffer resources: 0x7ad, usage: 0x219ff

info:  Creating sampler descriptor heap (32 kB)

info:  DXVK: Graphics pipeline libraries supported

011c:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.8" not implemented

011c:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.8" not implemented

info:  DXVK: Using 16 compiler threads

info:  D3D9DeviceEx: Using extended constant set for software vertex processing.

011c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION

info:  Creating resource descriptor heap (4096 kB)

info:  D3D9DeviceEx::ResetSwapChain:

info:    Requested Presentation Parameters

info:      - Width:              2560

info:      - Height:             1440

info:      - Format:             D3D9Format::A8R8G8B8

info:      - Auto Depth Stencil: true

info:                  ^ Format: D3D9Format::D24S8

info:      - Windowed:           false

info:      - Swap effect:        1

info:  Setting display mode: 2560x1440@120

info:  Setting display mode: 2560x1440@120

00a0:fixme:ntoskrnl:kernel_object_from_handle No constructor for type L"Token"

011c:fixme:combase:RoGetActivationFactory (L"Windows.Gaming.Input.RawGameController", {eb8d0792-e95a-4b19-afc7-0a59f8bf759e}, 00006FFFFDA38960): semi-stub

00cc:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION

warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 26

info:  Presenter: Actual swapchain properties:

info:    Format:       VK_FORMAT_B8G8R8A8_UNORM

info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR

info:    Present mode: VK_PRESENT_MODE_FIFO_KHR (dynamic: yes)

info:    Buffer size:  2560x1440

info:    Image count:  4

01bc:fixme:pulse:pulse_channel_map_to_channel_mask Unhandled channel aux2

01bc:fixme:pulse:pulse_channel_map_to_channel_mask Unhandled channel aux3

01bc:fixme:pulse:pulse_channel_map_to_channel_mask Unhandled channel aux2

01bc:fixme:pulse:pulse_channel_map_to_channel_mask Unhandled channel aux3

00a0:fixme:ntoskrnl:kernel_object_from_handle No constructor for type L"Token"

0128:fixme:keyboard:LoadKeyboardLayoutW name L"00000C09", flags 1, semi-stub!

0128:fixme:keyboard:X11DRV_ActivateKeyboardLayout 0xc090c09, 0000: semi-stub!

info:  Restoring display mode: 2560x1440@120

info:  Setting display mode: 2560x1440@120

info:  Restoring display mode: 1920x1080@60

info:  Setting display mode: 1920x1080@60

0128:err:sync:RtlLeaveCriticalSection section 004B8508 "?" is not acquired

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

0190:err:service:device_notify_proc failed to get event, error 1726

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory

Launch command: ['/usr/bin/gamemoderun', '/home/user/.config/heroic/tools/runtimes/umu/umu_run.py', '/home/user/Games/Heroic/Rayman 2/Rayman2.exe']

All processes exited

============= End of log =============

```

**Comment by spitfirex86** [comment]
Should be fixed now in v1.4.2: https://github.com/spitfirex86/Ray2Fix/releases/tag/v1.4.2

If it doesn't work still, try using the standalone installer instead of Galaxy.

**Comment by Jawzper** [comment]
I have tried the new patch now on my previous install, and also reinstalled from the standalone installer to try again. The issue is not fixed, widescreen does not work.

**Comment by spitfirex86** [comment]
You're kinda on your own with Wine, it's not my target. That being said, I've heard reports of it working on latest Wine with no other helpers or wrappers.

Is Ray2Fix even being loaded properly? Check the main menu of the game, the option "Site Rayman2" should be replaced with a version string for Ray2Fix. If it's not, something's gone wrong and the DLL fails to load.

Note that you need a recent version of the MSVC runtime to be installed.
